version: '3.8'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "seif"
      POSTGRES_PASSWORD: "seifPass"
      POSTGRES_DB: "testdb"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    networks:
      - app_network
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "saly@edu.hse.ru"
      PGADMIN_DEFAULT_PASSWORD: "seifpass"
    ports:
      - "5050:80"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge